version: "3.1"

services:
  # Database server
  dbserver:
      container_name: kcboi95_db
      image: mysql/mysql-server:8.0.13
      restart: always
      ports:
        - 3306:3306
      command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
      user: root
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./config/mysql.cnf:/etc/mysql/conf.d/config-file.cnf
        - ./htdocs:/var/www/html
      network_mode: bridge

  # Web server
  web:
      container_name: kcboi95_web
      build: .
      ports:
        - 80:80
        - 443:443
      depends_on:
        - dbserver
      volumes:
        - ./htdocs:/var/www/html
        # Mount PHP configs
        - ./etc/php7/fpm-pool.conf:/etc/php7/php-fpm.d/www.conf
        - ./etc/php7/php.ini:/etc/php7/conf.d/99.custom.ini
        - ./etc/php5/fpm-pool.conf:/etc/php5/php-fpm.conf
        - ./etc/php5/php.ini:/etc/php5/conf.d/99.custom.ini
        # Mount Nginx config
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
        - ./htdocs:/var/www/localhost/htdocs
        - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      network_mode: bridge
